# Generated by Django 4.2.5 on 2023-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_alter_place_options_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeID',
            field=models.SlugField(default='', max_length=100, verbose_name='ID места'),
        ),
        migrations.AddField(
            model_name='place',
            name='title_short',
            field=models.CharField(default='', max_length=40, verbose_name='Краткое название'),
        ),
    ]
