# Generated by Django 4.2.5 on 2023-09-11 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_placeid_place_title_short'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.AddField(
            model_name='image',
            name='image_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
