# Generated by Django 4.2.5 on 2023-09-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_description_long'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='place',
            options={'verbose_name': 'Локация', 'verbose_name_plural': 'Локации'},
        ),
        migrations.RemoveField(
            model_name='place',
            name='title_short',
        ),
        migrations.AlterField(
            model_name='place',
            name='title',
            field=models.CharField(help_text='Это название будет отображаться в виде заголовка в тексте)', max_length=200, unique=True, verbose_name='Название места'),
        ),
    ]
