# Generated by Django 4.2.5 on 2023-09-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0010_rename_description_long_place_long_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['order'], 'verbose_name': 'Изображение', 'verbose_name_plural': 'Изображения'},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_order',
            new_name='order',
        ),
    ]
